const colors = {
  light: {
    text: "#FFFFFF",
    tint: "#8C52FF",
    background: "#111111",
    foreground: "#FFFFFF",
    card: "#1A1A1A",
    cardForeground: "#FFFFFF",
    primary: "#8C52FF",
    primaryForeground: "#FFFFFF",
    secondary: "#1E1E1E",
    secondaryForeground: "#CCCCCC",
    muted: "#222222",
    mutedForeground: "#888888",
    accent: "#8C52FF",
    accentForeground: "#FFFFFF",
    destructive: "#ef4444",
    destructiveForeground: "#FFFFFF",
    border: "#333333",
    input: "#222222",
  },
  dark: {
    text: "#FFFFFF",
    tint: "#8C52FF",
    background: "#111111",
    foreground: "#FFFFFF",
    card: "#1A1A1A",
    cardForeground: "#FFFFFF",
    primary: "#8C52FF",
    primaryForeground: "#FFFFFF",
    secondary: "#1E1E1E",
    secondaryForeground: "#CCCCCC",
    muted: "#222222",
    mutedForeground: "#888888",
    accent: "#8C52FF",
    accentForeground: "#FFFFFF",
    destructive: "#ef4444",
    destructiveForeground: "#FFFFFF",
    border: "#333333",
    input: "#222222",
  },
  radius: 8,
};

export default colors;
